compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: /data2/xudong/wmj/video/LatentSync/configs/unet/unet_ds_config_for_accelerate.json
 zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
# mixed_precision: fp16   # 避免和deepspeed中的配置冲突
num_machines: 1
num_processes: 2
use_cpu: false